# Module: elasticsearch
# Docs: https://www.elastic.co/guide/en/beats/metricbeat/master/metricbeat-module-elasticsearch.html

- module: elasticsearch
  metricsets:
   - node
   - node_stats
  period: 10s
  hosts: [${ELASTIC_EXT_URL_1}]
  username: ${ELASTIC_USER}
  password: ${ELASTIC_PASSWORD}
  ssl.verification_mode: ${ELASTIC_SSL_VERIFICATION_MODE}
  enabled: true
