# Module: kibana
# Docs: https://www.elastic.co/guide/en/beats/metricbeat/master/metricbeat-module-kibana.html

- module: kibana
  metricsets:
   - status
  period: 10s
  hosts: ["192.168.1.104:5601"]
  basepath: ""
  username: "elastic"
  password: "elastic"
  enabled: true