setup.template.enabled: true
#---------------------------- APM Server ----------------------------
apm-server:
  host: "0.0.0.0:8200"
  ssl:
    enabled: true
    supportedProtocols: ["TLSv1.3"]
    # Certificate paths as mounted in the container.
    certificate: "/usr/share/apm-server/config/certs/es01/es01.crt"
    key: "/usr/share/apm-server/config/certs/es01/es01.key"
    certificate_authorities: ["/usr/share/apm-server/config/certs/ca/ca.crt"]
    client_authentication: "none"  # Disable client cert requirements: "optional"
    cipherSuites:
      - "TLS_AES_256_GCM_SHA384"
      - "TLS_CHACHA20_POLY1305_SHA256"
      - "TLS_AES_128_GCM_SHA256"
    verification_mode: "certificate"
    certificate_authorities : ["/usr/share/apm-server/config/certs/ca/ca.crt"]
    
#-------------------------- Elasticsearch output --------------------------
output.elasticsearch:
  # Array of hosts to connect to.
  hosts: ["https://es01:9200"]
  username: ${ELASTIC_USER}
  password: ${ELASTIC_PASSWORD}

  # SSL settings for Elasticsearch: Use certificate mode so that the CA is used to verify the chain.
  ssl:
    verification_mode: "certificate"
    certificate_authorities : ["/usr/share/apm-server/config/certs/ca/ca.crt"]

#---------------------------- APM Server - Agent Configuration ----------------------------
kibana:
  enabled: true
  host: "https://kibana:5601"
  username: "kibana_system"
  password: "elastic"

  ssl:
    enabled: true
    supportedProtocols: ["TLSv1.3"]
    # Adjusted certificate paths (remove duplicate slashes)
    certificate: "/usr/share/apm-server/config/certs/es01/es01.crt"
    key: "/usr/share/apm-server/config/certs/es01/es01.key"
    certificate_authorities: ["/usr/share/apm-server/config/certs/ca/ca.crt"]
    client_authentication: "none"  # Disable client cert requirements:
    cipherSuites:
      - "TLS_AES_256_GCM_SHA384"
      - "TLS_CHACHA20_POLY1305_SHA256"
      - "TLS_AES_128_GCM_SHA256"
    verification_mode: "certificate"  # allow chain verification without enforcing hostname match
    certificate_authorities : ["/usr/share/apm-server/config/certs/ca/ca.crt"]

#---------------------------- Logging -------------------------------
logging:
  level: debug
  to_stdout: true
  to_files: true
  files:
    path: /usr/share/apm-server/logs
    name: apm-server
    rotateeverybytes: 10485760
    keepfiles: 7
