server:
  name: kibana
  publicBaseUrl: https://kibana
  host: 0.0.0.0
  port: '5601'
  ssl:
    enabled: true
    # Only allow TLS 1.3
    supportedProtocols: ["TLSv1.3"]
    # Certificate paths
    certificate: "/usr/share/kibana/config/certs/es01/es01.crt"
    key: "/usr/share/kibana/config/certs/es01/es01.key"
    certificateAuthorities: ["/usr/share/kibana/config/certs/ca/ca.crt"]
    # Require client certificate authentication
    clientAuthentication: "optional"
    # Use modern cipher suites
    cipherSuites: [
      "TLS_AES_256_GCM_SHA384",
      "TLS_CHACHA20_POLY1305_SHA256",
      "TLS_AES_128_GCM_SHA256"
    ]

# Security settings
xpack.security:
  encryptionKey: "Gx45tR8dLpMnBv9cJh7kYp6sDf4eZxC2qA1wE3r"  # Must be at least 32 characters
  session:
    idleTimeout: "1h"
    lifespan: "24h"
  secureCookies: true

# Enable security features
xpack.encryptedSavedObjects:
  encryptionKey: "Gx45tR8dLpMnBv9cJh7kYp6sDf4eZxC2qA1wE3r"

# Enhanced security headers
server.securityResponseHeaders:
  strictTransportSecurity: "max-age=31536000; includeSubDomains"
  xContentTypeOptions: "nosniff"
  referrerPolicy: "strict-origin-when-cross-origin"
  permissionsPolicy: "accelerometer=(), camera=(), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), payment=(), usb=()"

# Elasticsearch connection settings
elasticsearch:
  hosts: ["https://es01:9200"]
  requestTimeout: 30000
  shardTimeout: 30000
  compression: false
  username: ""
  password: ""
  ssl:
    verificationMode: "none"