version: '3'

services:
  
  # Monitoring system
  metricbeat:
    container_name: metricbeat-erp
    hostname: metricbeat-erp
    image: docker.elastic.co/beats/metricbeat:8.1.0
    environment:
      - METRICBEAT_CONFIG_MODULES_PATH=/usr/share/metricbeat/modules.d
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro
      - /proc:/hostfs/proc:ro
      - /:/hostfs:ro
      - ./metricbeat_config:/tmp/metricbeat_config
      - ../template.sh:/tmp/template.sh
      - ../m_template.sh:/tmp/m_template.sh
      - ../.env:/tmp/.env
      - ./metricbeat.docker.yml:/usr/share/metricbeat/metricbeat.docker.yml
    command: >
      bash -c '
      chmod +x /tmp/template.sh &&
      chmod +x /tmp/m_template.sh &&
      cp /tmp/template.sh /bin/template.sh &&
      cp /tmp/m_template.sh /bin/m_template.sh &&
      cp -rT /usr/share/metricbeat/modules.d /usr/share/metricbeat/modules.backup.d &&
      cp /usr/share/metricbeat/metricbeat.yml /usr/share/metricbeat/metricbeat.yml.backup &&
      cp /usr/share/metricbeat/metricbeat.docker.yml /usr/share/metricbeat/metricbeat.yml &&
      cp -r /tmp/metricbeat_config/* /usr/share/metricbeat/modules.d &&
      cp /tmp/.env /usr/share/metricbeat/modules.d/.env &&
      m_template.sh /usr/share/metricbeat/modules.d &&
      cp /tmp/.env /usr/share/metricbeat/.env &&
      template.sh /usr/share/metricbeat/metricbeat.yml .env &&
      metricbeat -e -strict.perms=false
      '
    user: root

  filebeat:
    container_name: filebeat-erp
    hostname: filebeat-erp
    image: docker.elastic.co/beats/filebeat:8.1.0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - ./filebeat.docker.yml:/usr/share/filebeat/filebeat.docker.yml
      - ../template.sh:/usr/share/filebeat/template.sh
      - ../.env:/usr/share/filebeat/.env
    command: >
      bash -c '
      cp /usr/share/filebeat/filebeat.yml /usr/share/filebeat/filebeat.yml.backup &&
      cp /usr/share/filebeat/filebeat.docker.yml /usr/share/filebeat/filebeat.yml &&
      ./template.sh /usr/share/filebeat/filebeat.yml .env &&
      filebeat -e -strict.perms=false
      '
    user: root