filebeat.inputs:
- type: container
  paths: 
    - '/var/lib/docker/containers/*/*-json.log'

filebeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true

processors:
- add_docker_metadata: 
    host: "unix:///var/run/docker.sock"

output.elasticsearch:
  hosts: [${ELASTIC_EXT_URL_1}]
  pipeline: "set-error-flag"
  username: ${ELASTIC_USER}
  password: ${ELASTIC_PASSWORD}
  ssl.verification_mode: ${KIBANA_SSL_VERIFICATION_MODE}
  