setup.template.settings:
  index.number_of_shards: 1
  index.codec: best_compression
name: metricbeat-erp
metricbeat.modules:
- module: docker
  metricsets:
    - "container"
    - "cpu"
    - "diskio"
    - "event"
    - "healthcheck"
    - "info"
    #- "image"
    - "memory"
    - "network"
    #- "network_summary"
  hosts: ["unix:///var/run/docker.sock"]
  period: 10s
  enabled: true

output.elasticsearch:
  # Array of hosts to connect to.
  hosts: [${ELASTIC_EXT_URL_1}]

  # Protocol - either `http` (default) or `https`.
  protocol: ${PROTOCOL}

  # Authentication credentials - either API key or username/password.
  #api_key: "id:api_key"
  username: ${ELASTIC_USER}
  password: ${ELASTIC_PASSWORD}
  ssl.verification_mode: ${ELASTIC_SSL_VERIFICATION_MODE}

processors:
  - add_host_metadata: ~
  - add_cloud_metadata: ~
  - add_docker_metadata:
      host: "unix:///var/run/docker.sock"
  - add_kubernetes_metadata: ~
  - add_network_direction:
      source: source.ip
      destination: destination.ip
      target: network.direction
      internal_networks: [ private ]
  - add_process_metadata:
      match_pids: [system.process.ppid]
      target: system.process.parent

# =================================== Kibana ===================================
# Starting with Beats version 6.0.0, the dashboards are loaded via the Kibana API.
# This requires a Kibana endpoint configuration.
setup.kibana:
  host: ${KIBANA_EXT_URL_1}