filebeat.inputs:
- type: container
  paths: 
    - '/var/lib/docker/containers/*/*-json.log'

filebeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true

processors:
- add_docker_metadata: 
    host: "unix:///var/run/docker.sock"

output.elasticsearch:
  hosts: ["https://es01:9200"]
  username: "elastic"
  password: "elastic"
  ssl.verification_mode: "none"