metricbeat.config:
  modules:
    path: /usr/share/metricbeat/modules.d/*.yml
    reload.enabled: true

setup.template.settings:
  index.number_of_shards: 1

output.elasticsearch:
  hosts: ["https://es01:9200"]
  username: "elastic"
  password: "elastic"
  ssl.verification_mode: none

processors:
  - add_host_metadata: ~
  - add_cloud_metadata: ~
  - add_docker_metadata:
      host: "unix:///var/run/docker.sock"
  - add_kubernetes_metadata: ~
  - add_network_direction:
      source: source.ip
      destination: destination.ip
      target: network.direction
      internal_networks: [ private ]
  - add_process_metadata:
      match_pids: [system.process.ppid]
      target: system.process.parent
